# 应用名称
spring:
  application:
    name: map-service
  # nacos启动服务发现
  cloud:
    nacos:
      discovery:
        # 应用服务 WEB 访问端口
        server-addr: 127.0.0.1:8848

server:
  port: 8085

mmap:
  key: 0da3ae789f3510e6f823e28adb3268d1